Implemented fraud detection algorithm based on group specs
Oblako4/analytics pull request #3
Opened 2017-10-26 22:54 UTC by dktdaniel

2017-10-26 23:28 UTC, elenabartosh requested changes
Consider to add variables (const) that help to determine if transaction is fraudulent (number of devices, for example)

2017-10-26 23:36 UTC, elenabartosh approved these changes

2017-10-26 23:55 UTC, TiffyB reviewed
Looks good, just double-check that the quotes around template literals aren't turning values from integers to strings.

2017-10-27 02:11 UTC, dktdaniel commented
Looks like MySQL is saving them correctly to integers.

2017-10-27 22:23 UTC, merged